import { NextResponse } from 'next/server';

// Mock skills data — in production this would be fetched from the Hermes API server
const SKILLS = [
  {
    name: 'code-review',
    description: '代码审查 — 自动分析代码质量、安全漏洞和最佳实践',
    category: 'development',
    categoryLabel: '开发',
    source: 'built-in',
    tags: ['代码', '审查', '质量'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'api-design',
    description: 'API 设计 — RESTful/GraphQL API 设计与文档生成',
    category: 'development',
    categoryLabel: '开发',
    source: 'built-in',
    tags: ['API', '设计', '文档'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'test-gen',
    description: '测试生成 — 自动生成单元测试和集成测试',
    category: 'development',
    categoryLabel: '开发',
    source: 'built-in',
    tags: ['测试', '自动化', '单元测试'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'data-analysis',
    description: '数据分析 — 数据清洗、统计分析和可视化',
    category: 'data',
    categoryLabel: '数据',
    source: 'built-in',
    tags: ['数据', '分析', '可视化'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'sql-expert',
    description: 'SQL 专家 — SQL 查询优化和数据库设计',
    category: 'data',
    categoryLabel: '数据',
    source: 'built-in',
    tags: ['SQL', '数据库', '优化'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'doc-writer',
    description: '文档撰写 — 技术文档、API 文档和用户手册',
    category: 'creative',
    categoryLabel: '创作',
    source: 'built-in',
    tags: ['文档', '写作', '技术'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'translation',
    description: '翻译助手 — 多语言翻译和本地化',
    category: 'creative',
    categoryLabel: '创作',
    source: 'built-in',
    tags: ['翻译', '多语言', '本地化'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'mlops',
    description: 'MLOps — 机器学习模型训练、部署和监控',
    category: 'mlops',
    categoryLabel: 'MLOps',
    source: 'optional',
    tags: ['ML', '训练', '部署'],
    platforms: ['macos', 'linux'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'devops',
    description: 'DevOps — CI/CD、容器化、基础设施即代码',
    category: 'devops',
    categoryLabel: '运维',
    source: 'optional',
    tags: ['CI/CD', 'Docker', 'K8s'],
    platforms: ['macos', 'linux'],
    author: 'hermes',
    version: '1.0.0',
  },
  {
    name: 'security-audit',
    description: '安全审计 — 代码安全扫描和漏洞检测',
    category: 'security',
    categoryLabel: '安全',
    source: 'optional',
    tags: ['安全', '审计', '漏洞'],
    platforms: ['macos', 'linux', 'windows'],
    author: 'hermes',
    version: '1.0.0',
  },
];

export async function GET() {
  return NextResponse.json({ skills: SKILLS });
}
